# Generated by Django 4.1 on 2023-12-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KatalogBuku', '0004_auto_20231029_1734'),
        ('UserProfile', '0001_initial'),
        ('pinjambuku', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookloan',
            old_name='finished_date',
            new_name='done_date',
        ),
        migrations.RemoveField(
            model_name='bookloan',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loands', to='KatalogBuku.book'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loans', to='UserProfile.profile'),
        ),
    ]
