# Generated by Django 4.2.6 on 2023-10-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
        ('KatalogBuku', '0001_initial'),
        ('ForumDiskusi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='UserProfile.profile'),
        ),
        migrations.AddField(
            model_name='bookdiscussion',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_book', to='KatalogBuku.book'),
        ),
        migrations.AddField(
            model_name='bookdiscussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discussions', to='UserProfile.profile'),
        ),
    ]
