# Generated by Django 4.2.4 on 2023-10-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0002_profile_favorite_category_alter_profile_id'),
        ('KatalogBuku', '0001_initial'),
        ('ForumDiskusi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdiscussion',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_discussions', to='KatalogBuku.book'),
        ),
        migrations.AddField(
            model_name='bookdiscussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_discussions', to='UserProfile.profile'),
        ),
    ]
