# Generated by Django 4.2.4 on 2023-12-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumDiskusi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdiscussion',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
