# Generated by Django 4.2.4 on 2023-10-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumDiskusi', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdiscussion',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='discussioncomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.AddField(
            model_name='bookdiscussion',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bookdiscussion',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
