# Generated by Django 4.2.4 on 2023-10-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumDiskusi', '0004_alter_bookdiscussion_book_alter_bookdiscussion_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdiscussion',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
