# Generated by Django 4.2.4 on 2023-10-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumDiskusi', '0005_alter_bookdiscussion_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdiscussion',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
