# Generated by Django 4.2.6 on 2023-10-28 06:46


from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('KatalogBuku', '0001_initial'),
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_category',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='KatalogBuku.category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
