# Generated by Django 4.2.6 on 2023-10-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KatalogBuku', '0003_requestedbook'),
        ('UserProfile', '0003_rename_profile_img_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_category',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='KatalogBuku.category'),
        ),
    ]
